# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCriandoFiltros():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_criandoFiltros(self):
    self.driver.get("https://client-test-qa-frontend-neobiome-husrbtcmsa-ue.a.run.app/pt-BR/dashboard?customer=F016")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.LINK_TEXT, "Filtros Taxonômicos").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".e2e-add-TaxonomicFilter-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".e2e-add-TaxonomicFilter-button .mat-icon").click()
    self.driver.find_element(By.ID, "mat-input-1").click()
    self.driver.find_element(By.ID, "mat-input-1").send_keys("filtro gabrielle")
    self.driver.find_element(By.CSS_SELECTOR, ".mat-checkbox-inner-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-add-microrganisms").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-focused .mat-icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".mat-row:nth-child(7) .mat-focus-indicator")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-focused .mat-icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".mat-row:nth-child(10) .mat-focus-indicator")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".cdk-focused > .mat-button-wrapper > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".mat-button-wrapper > .ng-star-inserted:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".mat-button-wrapper > .ng-star-inserted:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
  
